version: "3" # composeファイルのバージョン
services:
  app: # サービス名
    build: ./docker/go/ # ビルドに使うDockerfileの場所
    tty: true # コンテナの永続化
    ports: # ホストOSのポートとコンテナのポートをつなげる
      - "3000:3000"
    volumes:
      - ./:/go/src/app # マウントディレクトリ
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build: ./docker/mysql/
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
#      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:3306